### PR TITLE
React slider field customizer

### PR DESCRIPTION
**Pull request by AJIXuMuK**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | no

#### What's in this Pull Request?

This project contains SharePoint Framework extensions that illustrates next features:
* field customizer
* usage of Office UI Fabric React
* usage of PnP JS
* inline editing of list items

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Alex, that was fast and appreciated the contributions. I'll slightly adjust the folder name for this sample, but otherwise all good. Would you be available for doing a quick demo around this one and the older popup panel web part demo in next Tuesday's June monthly community call at 8 AM PT?

**Comment by AJIXuMuK** [comment]
Hello Vesa,

Thanks for the opportunity, I'll be able to demo on Tuesday.

**Comment by VesaJuvonen** [comment]
thx Alex, I'll get you queued up for the demo in the shared agenda. You can, for example, show both - this one and dialog demo in the web parts side.

**Comment by AJIXuMuK** [comment]
Yup, I'll show both this one and Panel sample.

**Pull request merged**
