### PR TITLE
Site page core metadata footer extension

### PR DESCRIPTION
**Pull request by vipulkelkar**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        |                                |
| New feature?    |                                |
| New sample?     | YES                               |
| Related issues? |  |

## What's in this Pull Request?

Sample SharePoint Framework application customizer to display the core metadata of a Site Page such as Author,Editor, Created date and Modified date in the footer of the page.

## Guidance

Support for the page metadata was announced recently for the SharePoint modern pages. With this, a "Page Properties" webpart was also released that can be used to display the metadata of the site page on the page itself. 

However, at the time of writing this sample, the core metadata of the page such as Author, Created Date, Modified Date, Edited by etc is not available in the webpart.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Vipul, appreciated. This could be also a nice demo a community call if you are interested.  Sorry for the delay on processing.

**Comment by vipulkelkar** [comment]
Thanks @VesaJuvonen . Sure, I'll be interested in presenting this. Would that be tomorrow ?

**Comment by vipulkelkar** [comment]
No prob @VesaJuvonen  ...Any of the two slots works for me..

**Comment by vipulkelkar** [comment]
Hey @VesaJuvonen , any news on this :) ?

**Comment by VesaJuvonen** [comment]
Sorry - completely apparently forgot to confirm this... Yes - you'd have a spot tomorrow 25th of Oct for this demo. Thanks Vipul.

**Comment by vipulkelkar** [comment]
Ok...thanks Vesa !

**Pull request merged**
