### PR TITLE
QR Code List Item Command View Set

### PR DESCRIPTION
**Pull request by hugoabernier**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                                |
| New sample?     | yes                               |
| Related issues? | |

## What's in this Pull Request?

A list item command view set which generates a printable QR code for a list item.
QRCode

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Hi Hugo,

Loving your new sample, thank you so much for contributing it! Always a pleasure to merge your PRs. :)

Laura

**Comment by hugoabernier** [comment]
Thank you @LauraKokkarinen! Your feedback is always the highlight of every pull request!

**Comment by LauraKokkarinen** [comment]
Hi @hugoabernier ,

Would you like to show us a short demo about this sample in one of the future SPFx community calls?

Laura

**Comment by hugoabernier** [comment]
@LauraKokkarinen I would be delighted to! Let me know when

**Comment by LauraKokkarinen** [comment]
@hugoabernier Would the 24th of October work for you? Or the 7th of November?

L

**Comment by hugoabernier** [comment]
November 7th would be best, if you don't mind

**Comment by LauraKokkarinen** [comment]
Not at all! :) I'll note down that you'll be presenting a 10-15 min demo on that date. Cheers!

Laura

**Comment by LauraKokkarinen** [comment]
Hi @hugoabernier ,

It was just decided that we'll do some kind of an "Ignite special" call on the 7th of November and will not have any demos on that community call. I'm so sorry about having to cancel your demo that we've already agreed for that date! :( Would you be ok doing it some other time? There is still an open spot for a demo on the 24th of October, for example.

Laura

**Comment by hugoabernier** [comment]
@LauraKokkarinen I'm looking forward to an ignite special, so I don't mind being bumped. I'm not available on the 24 (will be on a plane) but I'm available any time after that

**Comment by hugoabernier** [comment]
@LauraKokkarinen I'm looking forward to an ignite special, so I don't mind being bumped. I'm not available on the 24 (will be on a plane) but I'm available any time after that. Just name a date and assume I'll be there.

**Comment by LauraKokkarinen** [comment]
@hugoabernier The 21st of November it is then. :) Thank you!

Laura

**Pull request merged**
