### PR TITLE
JS Command Clone

### PR DESCRIPTION
**Pull request by thechriskent**
| Q               | A
| --------------- | ---
| Bug fix?        | No
| New feature?    | No
| New sample?      | Yes
| Related issues?  | None

#### What's in this Pull Request?

Sample SharePoint Framework listview command set extension that allows users to clone one or more list items. Demonstrates conditional visibility, PnP JS Core requests, PnP JS Core Batching, and field specific formats for rest operations.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Chris. Let's do a demo on this one in the September monthly community call, like we chatted in another PR discussion. Simple and efficient 10-15 again on the capability.

**Comment by thechriskent** [comment]
Sounds great! Is this for the 7th or the 14th? Thanks!

**Comment by VesaJuvonen** [comment]
Monthly community calls are are the monthly summary calls on second Tuesday of each month - http://aka.ms/sppnp-call. Same idea as with SIGs, but to run through what has happened on the monthly level. September monthly call would be on Tuesday 12th of September at 8 AM PT. Your demo spot will follow the monthly summary with few other community demos in similar ways as with Thursday calls. Does that work?

**Comment by thechriskent** [comment]
Works great! Looking forward to it!

**Pull request merged**
