### PR TITLE
[react-msal-bot] SPFx Bot Extension using MSAL and Microsoft Graph

### PR DESCRIPTION
**Pull request by FranckyC**
| Q               | A
| --------------- | ---
| New sample?      | yes

#### What's in this Pull Request?
This sample demonstrates how to integrate a bot within a SharePoint Online portal supporting authentication to access Azure AD protected APIs like Microsoft graph resources. Behind the scenes, this sample implements the OAuth2 implicit grant flow using the MSAL JavaScript library.

### CODE REVIEW

**Comment by FranckyC** [comment]
@VesaJuvonen any update on this one?

**Comment by VesaJuvonen** [comment]
thx Franck, appreciated. This could be definitely a thing to demonstrate in the upcoming community calls, for example in the SPFx SIG on 18th, if you are interested and available.

**Comment by FranckyC** [comment]
@VesaJuvonen Yes sure, I'm in for the 18th!

**Comment by patrick-rodgers** [comment]
Hi @FranckyC - just wanted to double check you are still good to demo on call this Thursday Jan 18?

**Comment by FranckyC** [comment]
Hi @patrick-rodgers, yes sure, I'll be there!

**Comment by patrick-rodgers** [comment]
Awesome, thanks!

**Pull request merged**
