### PR TITLE
Added a new sample extension - Site Header Toggler

### PR DESCRIPTION
**Pull request by RamPrasadMeenavalli**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | NA |

## What's in this Pull Request?

Added a new application extension sample. This extension adds a toggler for the Site Header, using which users can show/hide the Site Header, to get more reading space

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @RamPrasadMeenavalli, appreciated.

**Comment by LauraKokkarinen** [comment]
Hi @RamPrasadMeenavalli ,

Would you be up for doing a 10-15 min demo about this sample on one of our upcoming SPFx community calls? https://aka.ms/spdev-spfx-call

We still have room in the call that happens on the 24th of October (Thursday next week) for example. Interested? :)

Laura

**Comment by RamPrasadMeenavalli** [comment]
> 
> 
> Hi @RamPrasadMeenavalli ,
> 
> Would you be up for doing a 10-15 min demo about this sample on one of our upcoming SPFx community calls? https://aka.ms/spdev-spfx-call
> 
> We still have room in the call that happens on the 24th of October (Thursday next week) for example. Interested? :)
> 
> Laura

Hi @LauraKokkarinen ,
Yes. I am interested to give a demo on this sample.

**Comment by LauraKokkarinen** [comment]
@RamPrasadMeenavalli Great! I'll mark you a spot on the call next Thursday (the 24th of October) then. :) Cheers!

Laura

**Pull request merged**
