### PR TITLE
Added react-command-form-settings sample

### PR DESCRIPTION
**Pull request by AhmadiRamin**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                              |
| New sample?     | yes                               |

## What's in this Pull Request?
New sample to redirect list forms

## Guidance

This extension provides settings for SharePoint list forms to redirect them to custom pages

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Really cool stuff. I'll though add a note on the readme that this is not actually quite recommended pattern and implementation will break when MS modifies the page dom. I get that this is currently the only way to achieve this if it's a critical requirement, so let's get it still in as a sample.... also demo is absolutely welcome, if you have availability in August/September time frame for the SPFx calls.

**Comment by VesaJuvonen** [comment]
hmm - I completely missed your comment already in the readme... so no need for me to add anything there. Thanks for sharing.

**Comment by AhmadiRamin** [comment]
Thanks @VesaJuvonen , I also forgot to update the title of readme, should I create a new pull request for that?
I'm available in August/September, so would glad to demo it :)

**Comment by VesaJuvonen** [comment]
Please submit a new PR for the name changes. How's your 29th of August? Would that work for you as a demo spot?

**Comment by AhmadiRamin** [comment]
29th of August is fine to me, thanks

**Comment by VesaJuvonen** [comment]
thx - adding you to the agenda.

**Pull request merged**
