### PR TITLE
Adds React Mega Menu created as Application Customizer SPFx Extension

### PR DESCRIPTION
**Pull request by VelinGeorgiev**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Adds React Mega Menu created as Application Customizer SPFx Extension.

#### Guidance
Please refer to the README.md file for more info.

Should you have any questions, please let me know. Cheers

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Velin, this has an unfortunate violation on the naming, since folder name should ALWAYS start with the used technology and it's pretty obvious that it's SPFx solution, since we are in spfx repository... so there's no need to repeat that in folder name - like mentioned in the contribution guidelines. I'll now merge this, but will update the folder name by removing that unnecessary prefix.

Other than that - would you be interested in doing a quick demo on this during next Thursday's community call? - This is cool setup and demonstrates how to use custom branding elements by using extensions.

**Comment by VelinGeorgiev** [comment]
Hey Vesa, thanks for fixing the folder name for me. I knew that I have to rename it, but of course forgot to do it before the pull request. Sorry about that.

Sure, I will join the community call and present it.

**Comment by VesaJuvonen** [comment]
thx Velin, looking forward to the demo.

**Comment by VelinGeorgiev** [comment]
Hi Vesa, there is a slight chance that I join in the middle of today's meeting. Can you add me as second or third demo just to be in the second half an hour just to ensure I am online.

Thanks,
Velin 

@VesaJuvonen

**Comment by VesaJuvonen** [comment]
thx for the heads up, let's do that. I'll push out the agenda on the afternoon to Twitter and will get you listed as the last demo person. All good.

**Comment by VelinGeorgiev** [comment]
Thanks a lot Vesa!

Cheers

**Pull request merged**
