### PR TITLE
react-command-generate-documents

### PR DESCRIPTION
**Pull request by russgove**
New sample

This project contains an azure function that can populate a word template stored in a document library with information passed into it in the post body. It can be used to add text, images, checkboxes and tables to a Word template. The function saves the generated document back to another SharePoint document library. The function impersonates the logged in user to ensure that the function only can write to libraries the caller has access to. It can also create a PDF version of the file using the v2.0 SharePoint rest interface. A sample SPFX list view command set is also included to demonstrate how to call the azure function. The replacement parameters in this sample came from a single list, but in real life they would likely come from multiple lists (order header/order detail).

### CODE REVIEW

**Comment by russgove** [comment]
enhancememnts to table handling

**Comment by LauraKokkarinen** [comment]
Hi @russgove ,

Unfortunately, we cannot accept this sample as it is currently. Please read and follow the contribution guidelines and make changes to your PR accordingly: https://github.com/SharePoint/sp-dev-fx-extensions/blob/master/.github/CONTRIBUTING.md

Also, I'd recommend you to remove the publishing profile, and other environment-specific things, from your PR.

Cheers!

Laura

**Comment by russgove** [comment]
Thanks ! I've  removed the publishing profile and cleaned up the README.

**Comment by russgove** [comment]
Hi Can this PR get Merged?

**Comment by hugoabernier** [comment]
Thank you @russgove for your patience while we processed your PR. 

This is a great sample, would you be interested in demoing it on an upcoming SPFx community call?

**Comment by russgove** [comment]
Hi hugo,
I can do that. just give me a couple of weeks as i need to st up my dev tenant.
russell

**Comment by hugoabernier** [comment]
That's great. Do you want to book a tentative date now, or would you prefer to set up your tenant first?

**Pull request merged**
