### PR TITLE
Sample added. App customiser using Text Analytics API from page comments

### PR DESCRIPTION
**Pull request by luismanez**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? | |

## What's in this Pull Request?
This PR adds a new sample. Sample shows how to get the comments in a page, and analyses the sentiment using Cognitive services Text Analytics API. The sentiment average is rendered as a rating component. (see sample readme for more detail and screenshot)

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx Luis, another really cool setup. Would you be interested in doing a live demo on this in future community calls?

**Comment by luismanez** [comment]
Hi Vesa. Always happy to do a live demo, but I´m gonna be 2 weeks on vacation since this monday. Could it be after that? (3rd Sept). Thanks!

**Comment by VesaJuvonen** [comment]
We could do this in the Sep monthly community call on 11th of Sep or in the SPFx community call on 13th of Sep. Your call. Both have a spot available and it's a cool sample once again to show an integration of SPFx and Azure services.

**Comment by luismanez** [comment]
13th Sept works for me! Cheers.

**Comment by VesaJuvonen** [comment]
Thanks Luis, appreciated. I'll get you scheduled for the 13th of Sep.

**Pull request merged**
