### PR TITLE
 Added a react-adal-bot sample + upgraded react-msal-bot

### PR DESCRIPTION
**Pull request by FranckyC**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                             |
| New sample?     | yes                           |

## What's in this Pull Request?

* Added a react-adal-bot to demonstrate how to integrate a bot in a SharePoint site using authentication with ADAL and auhtorization code flow accessing Microsfot Graph resources.
* Updated react-msal-bot + bug fixes + upgrade to 1.5.1

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thanks, Franck, really cool sample. Would you be interested in showing this in future SPFx community calls as a demo?

**Comment by FranckyC** [comment]
Hi @VesaJuvonen. Sure but I will be on vacation starting next monday to 17th September. I could do a demo after this date if spots are still available.

**Comment by FranckyC** [comment]
@VesaJuvonen Sure, I will be there!

**Comment by VesaJuvonen** [comment]
Thanks, @FranckyC  - I'll get you queued up for that. Enjoy the break.

**Comment by VesaJuvonen** [comment]
Thanks, @FranckyC - that settles it. TTYL.

**Pull request merged**
