### PR TITLE
Field customiser sample using the text analytics api

### PR DESCRIPTION
**Pull request by luismanez**
| Q               | A
| --------------- | ---
| Bug fix?        | no 
| New feature?    | no
| New sample?      | yes

#### What's in this Pull Request?

Sample SharePoint Framework list field customiser calling the Cognitive Services Text Analytics API and showing the _sentiment_ based on content, with an Icon.

This sample illustrates the following concepts on top of the SharePoint Framework:

* using Text Analytics API to get the sentiment score from a given Text
* using async / await for the async calls

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Luis, great sample and right on time for the January release, so getting this included in the Jan monthly notes. Would you be available and interested in demonstrating this on the 18th of January SharePoint Framework community call? - The typical timing at 3 PM GMT and with 15 min spot for the demo?

**Comment by luismanez** [comment]
Hi @VesaJuvonen, sure, happy to demo it during next community call. See you there!

**Comment by patrick-rodgers** [comment]
Hi @luismanez - just wanted to double check you are still good to demo on call this Thursday Jan 18?

**Comment by luismanez** [comment]
Hi @patrick-rodgers, yeah, still good to do it.

**Comment by patrick-rodgers** [comment]
Awesome, thanks!

**Pull request merged**
