### PR TITLE
New sample: react-command-page-model-pnpjs

### PR DESCRIPTION
**Pull request by fredupstair**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no               |
| New feature?    | no           |
| New sample?     | yes         |
| Related issues? | n.a.          |

## What's in this Pull Request?
New sample. SPFx extension using @pnp/pnpjs , that allows creating Modern Pages hard-coded or based on prefilled modern pages marked as "Page Model", inside the Site Pages Library.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @fredupstair, really cool setup. Would you be interested in doing a live demo of this in any of the upcoming SPFx community calls? Would be a nice sample to demonstrate and share the learnings.

**Comment by fredupstair** [comment]
Thank you for the merge @VesaJuvonen ! About the live demo, of course, I'd like to do it let me know when :)

**Comment by VesaJuvonen** [comment]
Hi @fredupstair, we would have 10-15 min spot in the 24th of April call if that works for you. We will have 3 demos in that call, so timing will be strict, but should be doable... to show the main behavior and then key points from the code. Works?

**Comment by fredupstair** [comment]
Hi @VesaJuvonen , that's ok! 10/15 minutes are fine, I'll try to do something simple but effective. Let me know any other details. Thank you so much :)

**Comment by VesaJuvonen** [comment]
Souds good - thx @fredupstair. I'll add you to the agenda related to this sample. Thx for volunteering.

**Comment by VesaJuvonen** [comment]
ah - it's btw 25th of April, not on 24th which hopefully does not have an impact on this.

**Comment by fredupstair** [comment]
no problem @VesaJuvonen , 25th is good as well :)

**Pull request merged**
