### PR TITLE
New sample - Command - Mail current view as image

### PR DESCRIPTION
**Pull request by anoopt**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                                |
| New sample?     |  yes                               |
| Related issues? | NA |

## What's in this Pull Request?

> This PR contains a sample for a list view command set which will send an email of the current list view (filtered or normal) as an image. Example use case - best used in combination with list view formatting i.e. create cool view formatting and mail them as an image to external users.

> The sample also has ability to share the image with internal users. If the internal users have access to the list then the sample gives an option to send a link to the view instead of sending the image.

#### Sharing is caring

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx Anoop, also a great blog post on this one. Would you be interested in doing a live demon this in our community calls?

**Comment by anoopt** [comment]
Thank you @VesaJuvonen . I am interested in doing a demo of this sample. Would it be on the 22nd?

**Comment by VesaJuvonen** [comment]
It could be already this week in 22nd of then next one at 6th of December. Depending on your availability and preference.

**Comment by anoopt** [comment]
Thank you @VesaJuvonen I will do the demo of this on 6th December as I need to get a couple of things ready for this sample. 

I can do the demo of [Convert to PDF](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/js-command-convert-to-pdf) and [Copy classic link](https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/js-command-copy-classic-link) on 22nd if there is a slot available?

**Comment by anoopt** [comment]
Hi @VesaJuvonen Just wanted to know if a slot is still available on 6th of December to do a demo of this extension?

**Pull request merged**
