### PR TITLE
React application botframework chat

### PR DESCRIPTION
**Pull request by stephanbisser**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | yes                              |
| New sample?     | yes                           |
| Related issues? | - |

## What's in this Pull Request?

SPFx application extension that uses the [Bot Framework React Webchat Component](https://www.npmjs.com/package/botframework-webchat#integrate-with-react) to render a Bot Framework chat window

## Guidance

You'll need an existing Bot Framework bot hosted in Azure to get the Direct Line key before

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Hi Stephan!

I'm trying to build this sample but I'm getting an error _'event-stream@3.3.6' is not in the npm registry_. Apparently it is because the version used by the solution contained a security vulnerability and has since been taken away from the npm registry. 

Could you try if the fixes mentioned in this Stackoverflow thread fix the issue? Thanks!
https://stackoverflow.com/questions/53578201/npm-err-404-not-found-event-stream3-3-6

Laura

**Comment by LauraKokkarinen** [comment]
There's also a _.yo-rc.json_ file in the samples root. Could you exclude that from the PR? Thanks!

Laura

**Comment by VesaJuvonen** [comment]
We would like to get this included in the repository, but would request few small changes. Any change we could make these happen @stephanbisser? Thx.

**Comment by stephanbisser** [comment]
Sorry for the late reply! I will do the changes today/tomorrow and update the PR to get this fixed...

**Comment by stephanbisser** [comment]
sorry taking longer than exptected, because now after removing node_modules npm install fails with

> gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1

and I wasn't able to fix it currently. will keep you posted...

**Comment by stephanbisser** [comment]
@LauraKokkarinen could you please check the PR again. I now removed the yo-rc.json and updated the dependencies...

**Comment by LauraKokkarinen** [comment]
Hi Stephan,

It's all good now! :) Thanks a lot for all the hard work you do!

Laura

**Comment by stephanbisser** [comment]
Thank you Laura! Always happy to contribute :)

**Pull request merged**
