### PR TITLE
added js-command-hide-commands

### PR DESCRIPTION
**Pull request by russgove**
New sample?     | Yes
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?

A sample extension that can be used to hide commands on list views.

### CODE REVIEW

**Comment by hugoabernier** [comment]
Hey @russgove, this looks like a cool sample, but I'm unsure whether we should encourage hiding buttons using this approach.

The general guidance is that you shouldn't ever manipulate the DOM for HTML that you don't own. In the case of commands in list views, the commands are either owned by SharePoint or custom commands.

If they are custom commands, the proper approach should be to enable/disable or hide/show from within your extension code.

How would we handle it if someone uses this extension on out-of-the-box commands and someone else from that organization opens a helpdesk ticket with Microsoft because they can't find the command that was hidden using the extension?

Can you think of a valid scenario that we could use to explain to the intended audience when this extension should be used in a **supportable** manner?

I'm sure there are valid scenarios, but I need your help identifying them.

**Comment by russgove** [comment]
Hi Hugo,
Valid points. As I mentioned in the readme this was developed at the
request of  user so that hide the out of the box commands so that we we
could focus users attention on the custom commands  that we had developed.
This could definitely cause support issues if used irresponsibly.

No problem if you don't take in the sample.   How do we do that, do you
decline it or do i cancel it somehow (i'm no github expert!)
Russell

**Comment by hugoabernier** [comment]
@russgove , no no, I think the sample is absolutely valuable. If you're ok with it, I'll add a little "support statement" in the README.MD and process your PR.

Does that work for you?

**Comment by russgove** [comment]
Sure, Hugo, you can do othat. I sort of already did at the bottom of the
readme, but if you think something more forceful is needed , go for it.
I'll also update the readme tomorrow and more clearly point out the reason
this was develeoped.

**Comment by russgove** [comment]
And it should be pointed out that if SPO let us reorder the commands in the
menu so that I could put mine up front, this solution would not even be
needed!

**Comment by hugoabernier** [comment]
Thank you @russgove! I'm sure a lot of people will find this sample useful.

I've updated the README.md file to re-iterate that this approach should be used with caution, but it is sometimes necessary.

> With great power comes great responsibility

😇

**Pull request merged**
