### PR TITLE
Lock Item Command Set Customizer

### PR DESCRIPTION
**Pull request by AJIXuMuK**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | no

#### What's in this Pull Request?

New sample - Lock Item Command Set Customizer

screen shot 2017-12-20 at 11 36 06 am

The sample illustrates the ability to lock/unlock selected item/document for the current user.
The lock is implemented as item's unique permissions set to Full Control for current user only.
The lock is available only for items that inherit permissions from the parent. Items with unique permissions can't be locked as we can't unlock them correctly later on.
All other permissions are deleted.
The Command is available only for users who have "Manage Permissions" permissions for the list/document library.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx Alex, this is a really great idea with a simple solution in the end, but great demo topic. Would you like to do a demo on this in the January monthly community call on 9th of January at 8 AM PT?

**Comment by AJIXuMuK** [comment]
Hi Vesa,
Thanks for the quick merge.
Yes, I will do a demo with a great pleasure.

**Comment by VesaJuvonen** [comment]
Thx Alex, I'll get you typical 10-15 min spot on the call. Have a great holiday and hopefully you'll have some time to relax during this time before we move to busy new year.

**Comment by AJIXuMuK** [comment]
Thnaks Vesa,

Merry Christmas and Happy New Year to you as well!
Have great time during the holidays with the family!

**Comment by VesaJuvonen** [comment]
Hi @AJIXuMuK - just to confirm. I'll get you a 10-15 min in the monthly call for live demo. Agenda will be going live on Monday 8th of January. Thx.

**Comment by AJIXuMuK** [comment]
Hi @VesaJuvonen,
Confirming that I'm available and ready to demo.

**Pull request merged**
