### PR TITLE
React Command Set to Get Thumbnail URL for file

### PR DESCRIPTION
**Pull request by aakashbhardwaj619**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | No                               |
| New feature?    | No                               |
| New sample?     | Yes                               |
| Related issues? | NA |

## What's in this Pull Request?

> React Get Thumbnail SPFx Command Set extension that uses Microsoft Graph API to get the Thumbnail URL, of selected size (small, medium, large), for any file stored in a SharePoint Document Library.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Awesome - thx @aakashbhardwaj619. Would you be interested on doing a demo on this in any of the upcoming community calls?

**Comment by aakashbhardwaj619** [comment]
Thanks Vesa. I would love to do the demo 😊

**Comment by aakashbhardwaj619** [comment]
> Awesome - thx @aakashbhardwaj619. Would you be interested on doing a demo on this in any of the upcoming community calls?

Hi @VesaJuvonen. Let me know when can I have a slot for doing this demo :)

**Comment by VesaJuvonen** [comment]
Thanks @aakashbhardwaj619  for following up on this - just got buried on the email inbox. We would have 10-15 min spots on 19th of Dec, 2nd of Jan or 16th of Jan for this one. You can pick based on your own availability. Let me know.

**Comment by aakashbhardwaj619** [comment]
19th of Dec works for me. Thanks 😊

**Comment by VesaJuvonen** [comment]
Excellent - thanks for confirming. 19th of Dec it is then. See you then.

**Pull request merged**
