### PR TITLE
New Sample - js-application-intranet-searchbox

### PR DESCRIPTION
**Pull request by MartinHatch**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | No                               |
| New feature?    | No                               |
| New sample?     | Yes                      |
| Related issues? | N/A |

## What's in this Pull Request?

New sample: **js-application-intranet-searchbox**

SPFx Application Customiser to add a new "Intranet Search" box to the header. This redirects search queries to the URL defined in the "Search Settings" as configured for the current site, allowing an integrated search control which takes users to a custom search results page.

Demonstrates use of

 - placeholders
 - spHttpUtility
 - SP Fabric Core
 - Compiled SCSS
 - localised strings.

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Hi @MartinHatch,

I was so looking forward to giving your extension a whirl but unfortunately there's a dependency that can no longer be found: https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz

Could you fix that, let me know, and I'll give it another go. :) Thanks!

Laura

**Comment by MartinHatch** [comment]
> Hi @MartinHatch,
> 
> I was so looking forward to giving your extension a whirl but unfortunately there's a dependency that can no longer be found: https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
> 
> Could you fix that, let me know, and I'll give it another go. :) Thanks!
> 
> Laura

Hi Laura

Weird as I didn't get any npm issues running a build.

Either way, I have updated package dependencies to the latest versions and committed. 
Is there anything else I need? (do I need to submit a fresh PR?)

**Comment by LauraKokkarinen** [comment]
Hi Martin,

Unfortunately the code still doesn't build due to this error: `Cannot find module '@microsoft/rush-stack-compiler-3.2'`. This seems to be related to using a non-default version of TypeScript in your project.

Could you fix this, please? Also, make sure to run `gulp clean` first if the code builds for you (you might have the file locally).

Thank you! :)

Laura

**Comment by MartinHatch** [comment]
@LauraKokkarinen 

Ok finally got what you mean after clearing down.
Seems I inadvertently increased various npm packages to newer versions. 

I've reverted back to the same versions you would find in a vanilla spfx build, and it is now working.

**Comment by LauraKokkarinen** [comment]
Hi Martin,

Now everything worked smoothly and I got to test your sample -- looks good! :) I'm sure it will be useful to many. I've now merged your PR. Sorry about the long delay due to summer vacations.

Thanks again and keep up the good work!

Laura

**Comment by VesaJuvonen** [comment]
@MartinHatch - just to follow up on this. You'd be more than welcome on doing a live demo of this in any of the upcoming SPFx community calls, if you have availability and interest. All of these demos are recorded and then posted to the SP Dev YouTube channel as isolated videos - for providing you addition visibility using our social media channels. 

This is not super complex scenario, but would be great to demo it and then pinpoint the key learnings from the code side, if possible.

Please let us know, if you are interested and we can check a suitable timing for it. Thx.

**Comment by MartinHatch** [comment]
Sounds good and I'd be happy to :)

On holiday at the moment but let's set this up when I'm back in a few days :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MartinHatch** [comment]
@VesaJuvonen : when would be the best time for the SPFx community call on this?

I'm available to do this whenever

**Comment by manoj2784** [comment]
@MartinHatch 
Thanks for this sample, it works perfectly fine. However, after adding this extension, intermittently we are getting blank page loads. On removing the externsion, the pages load correctly. Not sure what we are missing here. I'm sharing the http watch logs and console errors as well. Any help is much appreciated,
Thanks,
Manoj
Console-Capture

**Comment by VesaJuvonen** [comment]
@manoj2784 - please open up an issue and we can have a look on that potentially.

@MartinHatch  - apparently we never scheduled you to do the demo - I do apologize for that. What would be your availability to do that? We would have spots on the 13th of Feb and 27th of Feb calls for 10 min demos, if this still works for you.

**Comment by MartinHatch** [comment]
@VesaJuvonen Hi thanks :) 
Either date works for me, just let me know 👍

**Comment by PrasadKasireddy** [comment]
Related Issue #281

**Comment by VesaJuvonen** [comment]
@MartinHatch - Let's get you scheduled for the 27th of February then for a demo. Looking forward. I'll share the agenda few days before in social media and you'll be there.

**Comment by MartinHatch** [comment]
> @MartinHatch - Let's get you scheduled for the 27th of February then for a demo. Looking forward. I'll share the agenda few days before in social media and you'll be there.

@VesaJuvonen arggh  .. just realised this is going to clash ... 

Sorry for the short notice. Any chance we can bump to a different week?

**Comment by VesaJuvonen** [comment]
Please note that due the daylight savings time changes in US (summer time) - call is one hour earlier today than normally... which is reflected in the recurrent meeting invite https://aka.ms/spdev-spfx-call.

**Pull request merged**
