### PR TITLE
Fixed 'Title' of this application customizer.

### PR DESCRIPTION
**Pull request by rahulsuryawanshi**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | no                               |
| New sample?     | no                               |
| Documentation fix?     | yes                               |

## What's in this Pull Request?

> Fixed the title of this application customizer from "Tenant Global NavBar Application Customizer" to "Site Page Core Metadata Application Customizer" as title was incorrect.
>

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
Hi @rahulsuryawanshi ,

Has the change contained in the _config.yml ended up in this PR by accident? Could you exclude that? Thanks!

Laura

**Comment by rahulsuryawanshi** [comment]
@LauraKokkarinen 
I have only updated readme.md file of this project and I don't see that file in my local checkout or in Pull request. am I missing something here?

**Comment by rahulsuryawanshi** [comment]
Hi @LauraKokkarinen,

Looks like the file  _config.yml  was changed by @hugoabernier. 

@hugoabernier  - can you please help here?

Thanks 
Rahul

**Comment by hugoabernier** [comment]
Oh boy, sorry about that. It must've made the changes to _config.yml when I created the GitHub pages for aka.ms/spfx-extensions.

Feel free to omit that change.

**Comment by hugoabernier** [comment]
> Hi @LauraKokkarinen,
> 
> Looks like the file _config.yml was changed by @hugoabernier.
> 
> @hugoabernier - can you please help here?
> 
> Thanks
> Rahul

@rahulsuryawanshi It looks like I made the changes the day before you submitted your PR, so I suspect that your PR didn't include my changes, which is why it treats shows in your PR as a delete.

The changes to the _config.yml was necessary for the [aka.ms/spfx-extensions](https://aka.ms/spfx-extensions) site. 

If you exclude the changes from the _config.yml in your PR, there should be no more conflicts.

Sorry that this is more complicated than it should be. I guess that's the joy of contributing in a repo that has many active contributors :-)

**Comment by rahulsuryawanshi** [comment]
@LauraKokkarinen , @hugoabernier 
I am sorry for delayed response. I have submitted another pull request to remove config.yml file. I am not sure that is right approach. Please let me know if that is right approach or not.
Thanks again for your patience.

Rahul

**Pull request merged**
