### PR TITLE
JQuery-Application-Toastr updates

### PR DESCRIPTION
**Pull request by thechriskent**
| Q               | A
| --------------- | ---
| Bug fix?        | Yes
| New feature?    | No
| New sample?      | No
| Related issues?  | None

#### What's in this Pull Request?

- Updated the sample to take advantage of 1.1.3
- Temporarily disabled loading the service from a Barrel due to issue with WebPack file resolution
- Switched CSS colors to use theme syntax

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Chris, appreciated. This would be a great candidate to demo in next SPFx SIG call on 31st of August - if you have availability and interest.

**Comment by thechriskent** [comment]
Thanks Vesa, I'd love to demo this during the SIG call! Just let me know any details and I'll be ready.

As for updating the samples to use the latest options, I'd be happy to do this for more than just this one if that's something you think would be of value.

**Comment by VesaJuvonen** [comment]
We will release RC pretty soon, so would delay on upgrades until then. For the 31st of August - let's get you on the agenda for the demo based on this. Thx for volunteering.

**Comment by VesaJuvonen** [comment]
Hi Chris, just double checking to get final confirmation for the community call demo tomorrow Thursday 31st of August. We'd have 10-15 min for this or alternatively for cloning samples, whatever you prefer... just to demonstrate the capability and explain implementation. Both are cool samples - you could do this one in the SIG tomorrow and potentially clone sample in the September monthly community call? - Would that work?

So - 7 AM PT tomorrow works for you fine? We'll update you as a presenter in the call and move forward from there.

**Comment by thechriskent** [comment]
Absolutely! I'm excited for the call and will be ready. I'll stick to this sample for now, but would be happy to demo the cloning sample in September. Thanks!

**Pull request merged**
