### PR TITLE
Added CommandSet sample calling Cognitive Services Vision API

### PR DESCRIPTION
**Pull request by luismanez**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes

#### What's in this Pull Request?

This PR adds a new List view CommandSet extension sample, that shows how to call the Cognitive Services Vision API to get metadata about a selected image in a SP Library.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Luis, appreciated. Would you be interested in showing this in our monthly community call next Tuesday (10th of Sep at 7 AM PT) - we would give you typical 10-15 min to explain setup and walk through the demo and key code pieces.

**Comment by luismanez** [comment]
Hi @VesaJuvonen 
Thanks! yeah, sure, happy to do that, but only if you don't mind about my Spanglish, which is, from far, much much worse than your Finglish!

**Comment by VesaJuvonen** [comment]
Spanglish is absolutely fine and acceptable... it's any way around the content, not around perfect Oxford English... I'll get you queued up - thanks for doing this advance.

**Comment by luismanez** [comment]
Cool. Thanks Vesa. Just let me know the final date. 
Cheers!

**Comment by VesaJuvonen** [comment]
Monthly call is on next Tuesday at 8 AM PT... like always (2nd Tuesday of each month). You can download invite from http://aka.ms/sppnp-call. We'll upgrade you as a speaker when you join. I'll also add you to the agenda in our monthly communications, going live on Monday. Thx for doing this.

**Pull request merged**
