### PR TITLE
Upgraded sample to work with SPFx 1.6, code improvements etc

### PR DESCRIPTION
**Pull request by simonagren**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        |  yes                               |
| New feature?    |  no                               |
| New sample?     | no                                |

## What's in this Pull Request?
Made a new sample based on my old sample. 
That was in extension preview, with old PnPJs and old SPFx.

Now it's SpFx 1.6, PnPJs 1.2.1 and the current React.

Improved some of the code and separated some functions into a Helper-class.
Improved the way the dialog opens, more like the way it should.
Strings instead of hardcoded string. Both English and Swedish included.

Also changed to my actual twitter adress  👍 

/Simon

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Simon, appreciated. Would you be interested in showing this sample and code in one of the community calls? This is a good sample showing quite a few important topics and would be great to get it recorded.

**Comment by simonagren** [comment]
Sure Vesa, maybe we could talk about this further over email? :)
Send me an email: simon.agren@sogeti.se

**Comment by simonagren** [comment]
@VesaJuvonen Just wanted to let you know I sent an email response. Been having some troubles with emails not being sent properly. Let me know if you didn't get anything!

**Comment by VesaJuvonen** [comment]
Hi @simonagren - just a reminder that we will be sharing agenda in the hour around this having this demo in tomorrow's SIG - if you have any last minute changes in plans, please let me know.

**Comment by simonagren** [comment]
Hey @VesaJuvonen I'm gonna do a PR later with just a few changes, nothing drasticly.

- Added support for external users in the peoplepicker, 
- a few small UI changes,
- Async loading of the main component on button click.
- And in the demo I am using a field customizer to show how the permissions are changed for the user.

Think I'm gonna include the Field Customizer in the PR. But I'm gonna serve the solution, so no rush merging it!
Hope this is ok!

/Simon

**Pull request merged**
