### PR TITLE
React Overdue Tasks Application Customizer

### PR DESCRIPTION
**Pull request by AJIXuMuK**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | no

#### What's in this Pull Request?
React Overdue Tasks Application Customizer
screen shot 2017-07-05 at 8 52 27 pm

The sample illustrates how to display a warning message that current user has overdue tasks.

Features:
* application customizer
* usage of Page Placeholders
* usage of SP PnP JS

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Alex, great sample. Will add usage tracking image to readme, but otherwise all good.

**Comment by VesaJuvonen** [comment]
Hi Alex, would you be available to demonstrate this in August 2017 monthly community call on 8th of August at 8 AM PST? - Would be typical 10-15 min demo to show the capability and code. I know that this is a short notice, but hopefully good for you?

**Comment by AJIXuMuK** [comment]
Hi Vesa,
Yes, I'm available for the call. You can count on me.

**Comment by VesaJuvonen** [comment]
thx Alex, I'll get this included in agenda, which will be released later today together with August release notes.

**Pull request merged**
