### PR TITLE
Spfx Application Customiser 'Groups external links' Sample added

### PR DESCRIPTION
**Pull request by luismanez**
| Q               | A
| --------------- | ---
| Bug fix?        | no 
| New feature?    | no 
| New sample?      | yes

#### What's in this Pull Request?

This sample shows how to render a header navbar with some external links related to the Group the site is in, i.e: Group calendar, Notebook, Inbox, People...

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @luismanez. Simple, but quite powerful demo on two important topics - placeholders and Graph access. Would be we available for a demo on this one in one of the upcoming community calls with 10-15 min coverage on what does the solution actually do. 

Seems like a simple solution, but... it's simple for people who know SPFx - not for those who want to learn how to use it. In general, I can see plenty of similar solutions being built for customers, so would be great to get this covered in the community call. Thx.

**Comment by luismanez** [comment]
hey @VesaJuvonen. Happy to do that demo, but when would it be? just asking cos next week I´m attending the MVP Summit, so I´m not gonna be able to join the community call.
BTW, are you coming to the summit? would be great to meet in person :) 
Thanks.

**Comment by VesaJuvonen** [comment]
Next SPFx call is on 1st of March and then we have monthly community call on 13th of March. SPFx calls typically actually have slightly more audience - but both works and have free spots. I'll be in MVP summit for sure. Talking in few sessions, including Thursday - Post-55.

**Comment by luismanez** [comment]
If you don´t mind I prefer the 13th March, as this Thursday I´m pretty busy.
Great you´ll be in Summit. I´ll join your sessions. See you there!

**Comment by VesaJuvonen** [comment]
Hi Luis, that works as well... sorry for the small delay here, but let's schedule for the 13th of March community call. I'll add you to the agenda, which will be shared on Monday 12th of March. Thanks for volunteering on this one.

**Comment by luismanez** [comment]
All good @VesaJuvonen I´ll be ready for the demo. Speak you tomorrow.

**Pull request merged**
