### PR TITLE
QnA Chatbot using cognitive services

### PR DESCRIPTION
**Pull request by RodCoder**
| Q               | A
| --------------- | ---
| New sample?      | Yes

#### What's in this Pull Request?

SPFx application extension that uses Azure QnA cognitive services to efficiently answer FAQs.

#### Guidance
* Create new QnA Cognitive Service (https://qnamaker.ai/Documentation/quickstart)
Insert service key and knowledge base ID as per indicated in the readme file.

Thanks for your contribution! Sharing is caring.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Rodrigo, appreciated. Cool setup and also not too complex things at all... would you be available for a demo presentation of this in one of the upcoming community calls?

**Comment by RodCoder** [comment]
Hi Vesa, absolutely! Just let me know when would it be suitable and I'm in.

**Comment by VesaJuvonen** [comment]
Is this week's Thursday too soon? - That would be 1st of March at 3 PM GMT - in the normal bi-weekly SPFx call.

**Comment by VesaJuvonen** [comment]
FYI @patrick-rodgers

**Comment by patrick-rodgers** [comment]
Hi @RodCoder - let us know if you're interested, would be great to have you demo on the call!

**Comment by RodCoder** [comment]
Hi @VesaJuvonen @patrick-rodgers, always keen to help. I saw the call for speakers on Twitter so if you do need, I can prepare the demo tomorrow for the 1st of March!

**Comment by patrick-rodgers** [comment]
Awesome - you're on the agenda!

**Comment by VesaJuvonen** [comment]
Thx Rodrigo for doing this. I know that you have done this in the past, but just from consistently perspective, here's the process again  - Please join on the bi-weekly SPFx call - you can get the invite from https://aka.ms/sppnp-js-sig-call. We'll then upgrade you as a speaker for the call. We have 3 different community demos tomorrow and you'll be the first one to go around 20 past on the hour. The call will be recorded and shared from official SP Dev video channel at http://aka.ms/spdev-videos within 24 hours after the call. If you have any challenges on joining or getting access to call details, please let us know. Thx for volunteering on this one, really appreciated.

**Pull request merged**
